# Generated by Django 3.0.6 on 2020-05-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='descriptive name for creating pathways', max_length=64, unique=True)),
                ('label', models.CharField(help_text='text students will see on home page', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(help_text='can be path only', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderedApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='isp.App')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.Pathway')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_features', to='isp.Module')),
            ],
            options={
                'unique_together': {('name', 'module')},
            },
        ),
        migrations.AddField(
            model_name='app',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.Module'),
        ),
        migrations.CreateModel(
            name='EnabledFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.App')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_features', to='isp.Feature')),
            ],
            options={
                'unique_together': {('app', 'feature')},
            },
        ),
    ]
