# Generated by Django 3.0.6 on 2020-05-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='descriptive name for creating pathways', max_length=64, unique=True)),
                ('label', models.CharField(help_text='text students will see on home page', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(help_text='can be path only', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('constrain_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='isp.Class')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.School')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.Class')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.Pathway')),
            ],
        ),
        migrations.AddField(
            model_name='pathway',
            name='constrain_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='isp.School'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='constrain_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='isp.Teacher'),
        ),
        migrations.CreateModel(
            name='OrderedActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='isp.Activity')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.Pathway')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_features', to='isp.Module')),
            ],
            options={
                'unique_together': {('name', 'module')},
            },
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.Teacher'),
        ),
        migrations.AddField(
            model_name='activity',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.Module'),
        ),
        migrations.CreateModel(
            name='EnabledFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.Activity')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_features', to='isp.Feature')),
            ],
            options={
                'unique_together': {('activity', 'feature')},
            },
        ),
    ]
