# Generated by Django 3.0.6 on 2020-05-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classname',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
