# Generated by Django 3.0.6 on 2020-06-07 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0002_auto_20200606_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='constrain_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='isp.School'),
        ),
    ]
