# Generated by Django 3.0.6 on 2020-06-08 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0003_pathway_constrain_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
    ]
