# Generated by Django 3.0.6 on 2020-06-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0004_auto_20200608_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'My Classes'},
        ),
        migrations.AlterModelOptions(
            name='pathway',
            options={'verbose_name_plural': 'My Pathways'},
        ),
    ]
