# Generated by Django 3.0.6 on 2020-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0005_auto_20200609_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='foo', max_length=128),
            preserve_default=False,
        ),
    ]
