# Generated by Django 3.0.6 on 2020-06-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0006_student_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='pathway',
            options={},
        ),
    ]
