# Generated by Django 3.0.6 on 2020-06-09 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0007_auto_20200609_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isp.Pathway'),
        ),
    ]
