# Generated by Django 3.0.6 on 2020-06-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0008_auto_20200609_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='constrain_school',
        ),
    ]
