# Generated by Django 3.0.6 on 2020-06-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0010_pathway_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
