# Generated by Django 3.0.6 on 2020-06-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0011_auto_20200612_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='pathway',
            unique_together={('name', 'teacher')},
        ),
    ]
