# Generated by Django 3.0.6 on 2020-06-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0013_app_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['app__module'], 'verbose_name_plural': 'Activities'},
        ),
    ]
