# Generated by Django 3.0.6 on 2020-06-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0014_auto_20200612_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='app',
            name='url',
            field=models.CharField(help_text='can be path only', max_length=256),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
