# Generated by Django 3.0.6 on 2020-06-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0015_auto_20200612_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('school', 'name')},
        ),
    ]
