# Generated by Django 3.0.6 on 2020-06-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0015_auto_20200612_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='classcode',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
