# Generated by Django 3.0.6 on 2020-06-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0016_auto_20200625_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_type',
            field=models.CharField(choices=[('00_INSTR', 'Instruction'), ('10_WE', 'Worked Example'), ('20_GR', 'Guided Response')], default='00_INSTR', max_length=16),
        ),
        migrations.AlterField(
            model_name='app',
            name='module',
            field=models.CharField(choices=[('000_PRT', 'Pre-Training'), ('010_VV', 'Variables and Values'), ('020_RQ', 'Research Question'), ('030_HYPO', 'Hypothesis'), ('040_BRM', 'Basic Research'), ('050_PE', 'Procedures and Experimental Setup'), ('060_TED', 'TED'), ('070_MAT', 'Materials'), ('080_COND', 'Conduct'), ('090_DI', 'Data-Interpretation'), ('100_DC', 'Drawing Conclusions'), ('110_PSTR', 'Poster'), ('120_POT', 'Post-Training')], default='000_PRT', max_length=16),
        ),
    ]
