# Generated by Django 3.0.6 on 2020-06-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0016_auto_20200623_2154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pathway',
            unique_together=set(),
        ),
    ]
