# Generated by Django 3.0.6 on 2020-06-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0017_auto_20200623_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='edit_link',
            field=models.URLField(default='pathway/edit/', max_length=128, null=True),
        ),
    ]
