# Generated by Django 3.0.6 on 2020-06-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0017_auto_20200625_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['app__mod', 'app__app_type', 'name'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['mod', 'app_type', 'name']},
        ),
        migrations.RemoveField(
            model_name='app',
            name='module',
        ),
        migrations.AddField(
            model_name='app',
            name='mod',
            field=models.CharField(choices=[('000_PRT', 'Pre-Training'), ('010_VV', 'Variables and Values'), ('020_RQ', 'Research Question'), ('030_HYPO', 'Hypothesis'), ('035_PLAN', 'Plan Research'), ('040_BRM', 'Basic Research'), ('050_PE', 'Procedures and Experimental Setup'), ('060_TED', 'TED'), ('070_MAT', 'Materials'), ('080_COND', 'Conduct'), ('090_DI', 'Data-Interpretation'), ('100_DC', 'Drawing Conclusions'), ('110_PSTR', 'Poster'), ('120_POT', 'Post-Training')], default='000_PRT', max_length=16),
        ),
    ]
