# Generated by Django 3.0.6 on 2020-06-25 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0018_auto_20200625_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isp.Module'),
            preserve_default=False,
        ),
    ]
