# Generated by Django 3.0.6 on 2020-06-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0019_app_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['app__module__order', 'app__app_type', 'name'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['module__order', 'app_type', 'name']},
        ),
        migrations.RemoveField(
            model_name='app',
            name='mod',
        ),
    ]
