# Generated by Django 3.0.6 on 2020-06-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0019_auto_20200623_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='edit_link',
            field=models.URLField(default='pathway/edit', max_length=64, null=True),
        ),
    ]
