# Generated by Django 3.0.6 on 2020-06-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0020_auto_20200625_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='edit_link',
        ),
    ]
