# Generated by Django 3.0.6 on 2020-06-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0021_activitytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['app__module__order', 'activity_type__order', 'name'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='isp.ActivityType'),
            preserve_default=False,
        ),
    ]
