# Generated by Django 3.0.6 on 2020-06-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0022_auto_20200625_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['module__order', 'name']},
        ),
    ]
