# Generated by Django 3.0.6 on 2020-06-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0023_auto_20200625_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='app_type',
        ),
    ]
