# Generated by Django 3.0.6 on 2020-06-08 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200607_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'My Classes'},
        ),
        migrations.AlterModelOptions(
            name='pathway',
            options={'verbose_name_plural': 'My Pathways'},
        ),
        migrations.RemoveField(
            model_name='pathway',
            name='constrain_teacher',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
    ]
