# Generated by Django 3.0.6 on 2020-06-08 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200608_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pathway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Pathway'),
        ),
    ]
